create database LLC;

CREATE TABLE operations_receipts (
    id SERIAL PRIMARY KEY,
    file_path VARCHAR(500) NOT NULL,
    total Float NOT NULL,
    sub_total Float NOT NULL,
    tax Float NOT NULL,
    vendor VARCHAR(200) ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(200) NOT NULL
);
ALTER TABLE operations_receipts
ADD COLUMN company_name VARCHAR(200) NOT NULL;

ALTER TABLE operations_receipts
ADD COLUMN purchased_at TIMESTAMP ;

ALTER TABLE operations_receipts
ADD COLUMN vendor_address VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN customer_name VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN invoice_id VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN spend_type VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN sha256 VARCHAR(200) ;


ALTER TABLE LLC.operations_receipts ADD CONSTRAINT operations_receipts_unique UNIQUE KEY (sha256);


CREATE TABLE SHERIEF_SALE_MASTER_TABLE (
	ID INT NOT NULL AUTO_INCREMENT,
	FILE_HASH VARCHAR(255) NOT NULL,
	FILE_PATH VARCHAR(255) NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	PAGES_SIZE INT NOT NULL,
	UNIQUE KEY FILE_HASH (FILE_HASH) USING BTREE,
	PRIMARY KEY (ID)
);
ALTER TABLE SHERIEF_SALE_MASTER_TABLE
ADD SHERIFF_SALE_DATE DATE;