create database LLC;

CREATE TABLE operations_receipts (
    id SERIAL PRIMARY KEY,
    file_path VARCHAR(500) NOT NULL,
    total Float NOT NULL,
    sub_total Float NOT NULL,
    tax Float NOT NULL,
    vendor VARCHAR(200) ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(200) NOT NULL
);
ALTER TABLE operations_receipts
ADD COLUMN company_name VARCHAR(200) NOT NULL;

ALTER TABLE operations_receipts
ADD COLUMN purchased_at TIMESTAMP ;

ALTER TABLE operations_receipts
ADD COLUMN vendor_address VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN customer_name VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN invoice_id VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN spend_type VARCHAR(200) ;

ALTER TABLE operations_receipts
ADD COLUMN sha256 VARCHAR(200) ;


ALTER TABLE LLC.operations_receipts ADD CONSTRAINT operations_receipts_unique UNIQUE KEY (sha256);


CREATE TABLE SHERIEF_SALE_MASTER_TABLE (
	ID INT NOT NULL AUTO_INCREMENT,
	FILE_HASH VARCHAR(255) NOT NULL,
	FILE_PATH VARCHAR(255) NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	PAGES_SIZE INT NOT NULL,
	UNIQUE KEY FILE_HASH (FILE_HASH) USING BTREE,
	PRIMARY KEY (ID)
);
ALTER TABLE SHERIEF_SALE_MASTER_TABLE
ADD SHERIFF_SALE_DATE DATE;

ALTER TABLE SHERIEF_SALE_MASTER_TABLE
ADD UNIQUE INDEX unique_file_path (FILE_PATH);

CREATE TABLE SHERIEF_SALE_CHILD_TABLE (
	ID INT NOT NULL AUTO_INCREMENT,
	SHERIEF_SALE_MASTER_ID INT,
	FILE_HASH VARCHAR(255) NOT NULL,
	FILE_PATH VARCHAR(255) NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	CREATED_BY VARCHAR(255) NOT NULL,
	SHERIFF_SALE_DATE DATE NOT NULL,
	UNIQUE KEY FILE_HASH (FILE_HASH) USING BTREE,
	PRIMARY KEY (ID),
	CONSTRAINT fk_sherief_sale_master_id
		FOREIGN KEY (SHERIEF_SALE_MASTER_ID) REFERENCES SHERIEF_SALE_MASTER_TABLE(ID)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

ALTER TABLE SHERIEF_SALE_CHILD_TABLE
ADD UNIQUE INDEX unique_file_path (FILE_PATH);


CREATE TABLE SHERIEF_SALE_PROPERTY_TABLE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sale VARCHAR(255) ,
    case_number VARCHAR(255) ,
    sale_type VARCHAR(255) ,
    status VARCHAR(255) ,
    tracts VARCHAR(255) ,
    cost_tax_bid VARCHAR(255),
    plaintiff VARCHAR(255) ,
    attorney_for_plaintiff VARCHAR(255) ,
    defendant VARCHAR(255),
    property_address VARCHAR(255),
    municipality VARCHAR(255) ,
    parcel_tax_id VARCHAR(255) ,
    comments VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(200) NOT NULL DEFAULT 'SherifSale',
    SHERIEF_SALE_CHILD_ID INT,
    CONSTRAINT fk_sherief_sale_child_id
        FOREIGN KEY (SHERIEF_SALE_CHILD_ID) REFERENCES SHERIEF_SALE_CHILD_TABLE(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD ZILLOW_LINK VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD ZESTIMATE VARCHAR(20);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD ZESTIBUCK VARCHAR(50);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD COLUMN EVENTS TEXT;

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD COLUMN SCHOOLS TEXT;

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD YEAR_BUILT VARCHAR(50);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD LOT_SIZE VARCHAR(80);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD SQUARE_FOOT_RANGE VARCHAR(80);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD SQUARE_FOOT VARCHAR(80);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD BEDROOMS VARCHAR(5);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD BATHROOMS VARCHAR(5);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD HOME_TYPE VARCHAR(80);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD HEATING VARCHAR(100);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD COOLING VARCHAR(100);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD PARKING VARCHAR(100);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD EXTERIOR VARCHAR(100);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD PARCEL_NUM VARCHAR(200);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD CONSTRUCTION_MATERIALS VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD ROOF VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD STREET VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD CITY VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD STATE VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD ZIP VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD COUNTY VARCHAR(300);

ALTER TABLE SHERIEF_SALE_PROPERTY_TABLE
ADD AMOUNT_IN_DISPUTE VARCHAR(50);


